[package]
name = "ozz-rust"
version = "0.1.0"
authors = ["FenQiDian <email@fenqi.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
approx = "0.5.1"
bitvec = "1.0.0"
maplit = "1.0.2"
nalgebra = "0.31.0"
